Repository google/automl, pull requests merged in 2020-08, with the labels that each got.

#645 Allow exporting saved model for network.
  efficientdet/model_inspect.py
Labels: cla: yes

#647 A few cleanups on jitter and inspect tools.
  efficientdet/dataloader.py
  efficientdet/det_model_fn.py
  efficientdet/g3doc/faq.md
  efficientdet/hparams_config.py
  efficientdet/inference.py
  efficientdet/keras/train_lib.py
  efficientdet/keras/train_lib_test.py
  efficientdet/keras/utils_keras_test.py
  efficientdet/utils.py
Labels: cla: yes

#644 Update README.md
  efficientdet/README.md
Labels: cla: yes

#652 Sync
  efficientdet/tensorrt.py
Labels: cla: yes

#651 fix seg loss
  efficientdet/hparams_config.py
  efficientdet/keras/train_lib.py
  efficientdet/keras/train_lib_test.py
Labels: cla: yes

#655 Internal changes
  efficientdet/det_model_fn.py
  efficientdet/keras/efficientdet_keras.py
  efficientdet/keras/train_lib_test.py
  efficientdet/keras/util_keras.py
  efficientdet/keras/util_keras_test.py
  efficientdet/main.py
  efficientdet/utils.py
Labels: cla: yes

#643 Multi scale tta
  efficientdet/keras/eval.py
  efficientdet/keras/wbf.py
  efficientdet/keras/wbf_test.py
Labels: cla: yes

#654 Fix preprocessing error in keras infer
  efficientdet/keras/infer.py
Labels: cla: yes

#656 fix diou and ciou norm calculate
  efficientdet/iou_utils.py
  efficientdet/iou_utils_test.py
Labels: cla: yes

#661 Allow irregular shape inputs.
  efficientdet/iou_utils_test.py
  efficientdet/keras/efficientdet_keras.py
  efficientdet/keras/efficientdet_keras_test.py
  efficientdet/keras/eval.py
  efficientdet/keras/train_lib_test.py
  efficientdet/keras/wbf.py
  efficientdet/keras/wbf_test.py
  efficientdet/tensorrt.py
Labels: cla: yes

#662 Use keras model in default and add gradient value and loss clipping.
  efficientdet/det_model_fn.py
  efficientdet/hparams_config.py
  efficientdet/keras/efficientdet_keras.py
Labels: cla: yes

#663 Add per-class AP metrics.
  efficientdet/coco_metric.py
  efficientdet/det_model_fn.py
  efficientdet/keras/eval.py
Labels: cla: yes

#665 Speedup keras eval.
  efficientdet/keras/eval.py
Labels: cla: yes

#675 Add number of epoch into logging message
  efficientdet/main.py
Labels: cla: yes

#672 add ckpt_path to export best model
  efficientdet/README.md
Labels: cla: yes

#678 Fix an issue which prevents EarlyStopping callback
  efficientdet/keras/train_lib.py
Labels: cla: yes

#677 Separating input and output model checkpoint, avoiding file overwriting.
  efficientdet/keras/train.py
  efficientdet/keras/train_lib.py
Labels: cla: yes

#679 fix pretrained_ckpt None bug
  efficientdet/keras/train.py
Labels: cla: yes

#693 :wrench: var_freeze pattern warning if none variables matched.
  efficientdet/efficientdet_arch.py
Labels: cla: yes

#682 Add instruction for re-train model
  efficientdet/README.md
  efficientdet/g3doc/faq.md
Labels: cla: yes

#696 Update efficientdet_arch.py freeze_vars error
  efficientdet/efficientdet_arch.py
Labels: P1, cla: yes

#701 Added Mosaic Augmentation in core TF
  efficientdet/aug/mosaic.py
  efficientdet/aug/mosaic_test.py
Labels: cla: yes, enhancement

#706 add option run_epoch_in_child_process
  efficientdet/main.py
Labels: cla: yes

#708 fix keras export saved model
  efficientdet/backbone/efficientnet_builder.py
  efficientdet/backbone/efficientnet_lite_builder.py
  efficientdet/backbone/efficientnet_model.py
  efficientdet/efficientdet_arch.py
  efficientdet/keras/efficientdet_keras.py
  efficientdet/keras/infer.py
Labels: cla: yes
